Fix bug "undefined method `exists' for class `Watir::IE' (NameError)" introduced in previous commit.
git-svn-id: https://svn.openqa.org/svn/watir/trunk@1054 deaf61b0-630d-0410-ad59-fc55e6353476